const GENRE_LOADING = 'GENRE_LOADING'
const GENRE_LOADED = 'GENRE_LOADED'
const GENRE_ERROR = 'GENRE_ERROR'

const GENRES_LOADING = 'GENRES_LOADING'
const GENRES_LOADED = 'GENRES_LOADED'
const GENRES_ERROR = 'GENRES_ERROR'

const GENRE_FILMS_LOADING = 'GENRE_FILMS_LOADING'
const GENRE_FILMS_LOADED = 'GENRE_FILMS_LOADED'
const GENRE_FILMS_ERROR = 'GENRE_FILMS_ERROR'

export default {
	GENRE_LOADING,
	GENRE_LOADED,
	GENRE_ERROR,
	GENRES_LOADING,
	GENRES_LOADED,
	GENRES_ERROR,
	GENRE_FILMS_LOADING,
	GENRE_FILMS_LOADED,
	GENRE_FILMS_ERROR,
}
