const GENRE_LOADING = 'GENRE_LOADING'
const GENRE_LOADED = 'GENRE_LOADED'
const GENRES_LOADED = 'GENRES_LOADED'
const GENRE_ERROR = 'GENRE_ERROR'

export default {
	GENRE_LOADING,
	GENRE_LOADED,
	GENRES_LOADED,
	GENRE_ERROR,
}
