const CALENDAR_LOADING = 'CALENDAR_LOADING';
const CALENDAR_LOADED = 'CALENDAR_LOADED';
const CALENDAR_ERROR = 'CALENDAR_ERROR';
const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
const ADD_TO_FAVORITES_ERROR = 'ADD_TO_FAVORITES_ERROR';
const DELETE_FROM_FAVORITES_ERROR = 'DELETE_FROM_FAVORITES_ERROR';

export default {
	CALENDAR_LOADING,
	CALENDAR_LOADED,
	CALENDAR_ERROR,
	ADD_TO_FAVORITES,
	DELETE_FROM_FAVORITES,
	ADD_TO_FAVORITES_ERROR,
	DELETE_FROM_FAVORITES_ERROR,
} as const;
