const CALENDAR_LOADING = 'CALENDAR_LOADING';
const CALENDAR_LOADED = 'CALENDAR_LOADED';
const CALENDAR_ERROR = 'CALENDAR_ERROR';

export default {
	CALENDAR_LOADING,
	CALENDAR_LOADED,
	CALENDAR_ERROR,
} as const;
