const FAVORITES_LOADING = 'FAVORITES_LOADING';
const FAVORITES_LOADED = 'FAVORITES_LOADED';
const FAVORITES_ERROR = 'FAVORITES_ERROR';

export default {
	FAVORITES_LOADING,
	FAVORITES_LOADED,
	FAVORITES_ERROR,
} as const;
