const FAVORITES_LOADING = 'FAVORITES_LOADING';
const FAVORITES_LOADED = 'FAVORITES_LOADED';
const FAVORITES_ERROR = 'FAVORITES_ERROR';
const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const ADD_TO_FAVORITES_ERROR = 'ADD_TO_FAVORITES_ERROR';
const DELETE_FROM_FAVORITES_ERROR = 'DELETE_FROM_FAVORITES_ERROR';

export default {
	FAVORITES_LOADING,
	FAVORITES_LOADED,
	FAVORITES_ERROR,
	DELETE_FROM_FAVORITES,
	DELETE_FROM_FAVORITES_ERROR,
	ADD_TO_FAVORITES,
	ADD_TO_FAVORITES_ERROR,
} as const;
