const FILMS_LOADING = 'FILMS_LOADING';
const FILMS_LOADED = 'FILMS_LOADED';
const FILMS_ERROR = 'FILMS_ERROR';
const FILMS_CLEAR = 'FILMS_CLEAR';

const RECOMMENDATIONS_LOADING = 'RECOMMENDATIONS_LOADING';
const RECOMMENDATIONS_LOADED = 'RECOMMENDATIONS_LOADED';
const RECOMMENDATIONS_ERROR = 'RECOMMENDATIONS_ERROR';

export default {
	FILMS_LOADING,
	FILMS_LOADED,
	FILMS_ERROR,
	FILMS_CLEAR,

	RECOMMENDATIONS_LOADING,
	RECOMMENDATIONS_LOADED,
	RECOMMENDATIONS_ERROR,
} as const;
