const FILM_LOADING = 'FILM_LOADING';
const FILM_LOADED = 'FILM_LOADED';
const FILM_ERROR = 'FILM_ERROR';
const CLEAR_FILM = 'CLEAR_FILM';

const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
const FEEDBACK_LOADED = 'FEEDBACK_LOADED';
const FEEDBACK_ERROR = 'FEEDBACK_ERROR';

const CREATE_FEEDBACK = 'CREATE_FEEDBACK';
const CREATE_RATING = 'CREATE_RATING';
const CREATE_FEEDBACK_ERROR = 'CREATE_FEEDBACK_ERROR';
const CREATE_RATING_ERROR = 'CREATE_RATING_ERROR';

const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
const ADD_TO_FAVORITES_ERROR = 'ADD_TO_FAVORITES_ERROR';
const DELETE_FROM_FAVORITES_ERROR = 'DELETE_FROM_FAVORITES_ERROR';

export default {
	FILM_LOADING,
	FILM_LOADED,
	FILM_ERROR,
	CLEAR_FILM,

	FEEDBACK_LOADING,
	FEEDBACK_LOADED,
	FEEDBACK_ERROR,

	CREATE_FEEDBACK,
	CREATE_RATING,
	CREATE_FEEDBACK_ERROR,
	CREATE_RATING_ERROR,

	ADD_TO_FAVORITES,
	DELETE_FROM_FAVORITES,
	ADD_TO_FAVORITES_ERROR,
	DELETE_FROM_FAVORITES_ERROR,
} as const;
