const FILM_LOADING = 'FILM_LOADING';
const FILM_LOADED = 'FILM_LOADED';
const FILM_ERROR = 'FILM_ERROR';
const CLEAR_FILM = 'CLEAR_FILM';

const FEEDBACK_LOADING = 'FEEDBACK_LOADING';
const FEEDBACK_LOADED = 'FEEDBACK_LOADED';
const FEEDBACK_ERROR = 'FEEDBACK_ERROR';

export default {
	FILM_LOADING,
	FILM_LOADED,
	FILM_ERROR,
	CLEAR_FILM,

	FEEDBACK_LOADING,
	FEEDBACK_LOADED,
	FEEDBACK_ERROR,
} as const;
