const FILMS_LOADING = 'FILMS_LOADING'
const FILMS_LOADED = 'FILMS_LOADED'
const FILMS_ERROR = 'FILMS_ERROR'
const FILMS_CLEAR = 'FILMS_CLEAR'

export default {
	FILMS_LOADING,
	FILMS_LOADED,
	FILMS_ERROR,
	FILMS_CLEAR,
}
