const USER_CREATE = 'USER_CREATE';
const USER_UPDATE = 'USER_UPDATE';
const USER_DELETE = 'USER_DELETE';
const USER_LOADING = 'USER_LOADING';
const USER_LOADED = 'USER_LOADED';
const USER_ERROR = 'USER_ERROR';
const USER_LOGOUT = 'USER_LOGOUT';
const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';
const AVATAR_CHANGE_ERROR = 'AVATAR_CHANGE_ERROR';

export default {
	USER_CREATE,
	USER_UPDATE,
	USER_DELETE,
	USER_LOADING,
	USER_LOADED,
	USER_ERROR,
	USER_LOGOUT,
	PASSWORD_CHANGE_ERROR,
	AVATAR_CHANGE_ERROR,
} as const;
