const USER_CREATE = 'USER_CREATE';
const USER_UPDATE = 'USER_UPDATE';
const USER_DELETE = 'USER_DELETE';
const USER_LOADING = 'USER_LOADING';
const USER_LOADED = 'USER_LOADED';
const USER_ERROR = 'USER_ERROR';
const USER_ERROR_RESET = 'USER_ERROR_RESET';
const USER_LOGOUT = 'USER_LOGOUT';
const PASSWORD_CHANGE_ERROR = 'PASSWORD_CHANGE_ERROR';
const PASSWORD_CHANGE_LOADING = 'PASSWORD_CHANGE_LOADING';
const PASSWORD_CHANGE_LOAD = 'PASSWORD_CHANGE_LOAD ';
const AVATAR_CHANGE_ERROR = 'AVATAR_CHANGE_ERROR';
const AVATAR_CHANGE_LOADING = 'AVATAR_CHANGE_LOADING';
const AVATAR_CHANGE_LOAD = 'AVATAR_CHANGE_LOAD';
const USER_OTP_ACTIVATE = 'USER_OTP_ACTIVATE';
const USER_OTP_DEACTIVATE = 'USER_OTP_DEACTIVATE';
const USER_OTP_LOADING = 'USER_OTP_LOADING';
const USER_OTP_ERROR = 'USER_OTP_ERROR';
const USER_CHECKED = 'USER_CHECKED';

const VKID_USER_LOADED = 'VKID_USER_LOADED';
const VKID_USER_ERROR = 'VKID_USER_ERROR';
const VKID_USER_ERROR_CLEAR = 'VKID_USER_ERROR_CLEAR';

export default {
	VKID_USER_LOADED,
	VKID_USER_ERROR,
	VKID_USER_ERROR_CLEAR,
	USER_CREATE,
	USER_UPDATE,
	USER_DELETE,
	USER_LOADING,
	USER_LOADED,
	USER_ERROR,
	USER_ERROR_RESET,
	USER_LOGOUT,
	PASSWORD_CHANGE_ERROR,
	PASSWORD_CHANGE_LOADING,
	PASSWORD_CHANGE_LOAD,
	AVATAR_CHANGE_ERROR,
	AVATAR_CHANGE_LOADING,
	AVATAR_CHANGE_LOAD,
	USER_OTP_ACTIVATE,
	USER_OTP_DEACTIVATE,
	USER_OTP_LOADING,
	USER_OTP_ERROR,
	USER_CHECKED,
} as const;
