const USER_CREATE = 'USER_CREATE'
const USER_UPDATE = 'USER_UPDATE'
const USER_DELETE = 'USER_DELETE'
const USER_LOADING = 'USER_LOADING'
const USER_LOADED = 'USER_LOADED'
const USER_ERROR = 'USER_ERROR'

export default {
	USER_CREATE,
	USER_UPDATE,
	USER_DELETE,
	USER_LOADING,
	USER_LOADED,
	USER_ERROR,
}
