export const DESKTOP_MIN_WIDTH = 1280;

export const TABLET_MIN_WIDTH = 1024;

export const SMALL_TABLET_MIN_WIDTH = 768;

export const MOBILE_MIN_WIDTH = 320;

export const SMALL_MOBILE_MAX_WIDTH = 320;

export const ADAPTIVITIES = {
	DESKTOP: 'DESKTOP',
	TABLET: 'TABLET',
	SMALL_TABLET: 'SMALL_TABLET',
	MOBILE: 'MOBILE',
	SMALL_MOBILE: 'SMALL_MOBILE',
};
