const SEARCH_LOADING = 'SEARCH_LOADING';
const SEARCH_LOADED = 'SEARCH_LOADED';
const SEARCH_ERROR = 'SEARCH_ERROR';
const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
const VOICE_SEARCH_LOADED = 'VOICE_SEARCH_LOADED';
const CLEAR_VOICE_SEARCH_RESULT = 'CLEAR_VOICE_SEARCH_RESULT';
const VOICE_SEARCH_IS_WORKING = 'VOICE_SEARCH_IS_WORKING';
const VOICE_SEARCH_STOPPED = 'VOICE_SEARCH_STOPPED';

export default {
	SEARCH_LOADING,
	SEARCH_LOADED,
	SEARCH_ERROR,
	CLEAR_SEARCH_RESULT,
	VOICE_SEARCH_LOADED,
	CLEAR_VOICE_SEARCH_RESULT,
	VOICE_SEARCH_IS_WORKING,
	VOICE_SEARCH_STOPPED,
} as const;
