const SEARCH_LOADING = 'SEARCH_LOADING';
const SEARCH_LOADED = 'SEARCH_LOADED';
const SEARCH_ERROR = 'SEARCH_ERROR';
const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';

export default {
	SEARCH_LOADING,
	SEARCH_LOADED,
	SEARCH_ERROR,
	CLEAR_SEARCH_RESULT,
} as const;
