const COMPILATION_LOADING = 'COMPILATION_LOADING';
const COMPILATION_LOADED = 'COMPILATION_LOADED';
const COMPILATION_ERROR = 'COMPILATION_ERROR';

const COMPILATIONS_LOADING = 'COMPILATIONS_LOADING';
const COMPILATIONS_LOADED = 'COMPILATIONS_LOADED';
const COMPILATIONS_ERROR = 'COMPILATIONS_ERROR';

const COMPILATION_FILMS_LOADING = 'COMPILATION_FILMS_LOADING';
const COMPILATION_FILMS_LOADED = 'COMPILATION_FILMS_LOADED';
const COMPILATION_FILMS_ERROR = 'COMPILATION_FILMS_ERROR';
const CLEAR_COMPILATION = 'CLEAR_COMPILATION';

const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
const ADD_TO_FAVORITES_ERROR = 'ADD_TO_FAVORITES_ERROR';
const DELETE_FROM_FAVORITES_ERROR = 'DELETE_FROM_FAVORITES_ERROR';

export default {
	COMPILATION_LOADING,
	COMPILATION_LOADED,
	COMPILATION_ERROR,
	COMPILATIONS_LOADING,
	COMPILATIONS_LOADED,
	COMPILATIONS_ERROR,
	COMPILATION_FILMS_LOADING,
	COMPILATION_FILMS_LOADED,
	COMPILATION_FILMS_ERROR,
	CLEAR_COMPILATION,
	ADD_TO_FAVORITES,
	DELETE_FROM_FAVORITES,
	ADD_TO_FAVORITES_ERROR,
	DELETE_FROM_FAVORITES_ERROR,
} as const;
