const TODOS_FETCH_START = 'FETCH_START'
const TODOS_FETCH_SUCCESS = 'FETCH_SUCCESS'
const TODOS_FETCH_FAILURE = 'FETCH_FAILURE'

export default {
	TODOS_FETCH_START,
	TODOS_FETCH_SUCCESS,
	TODOS_FETCH_FAILURE,
}
