const TOP_FILM_LOADING = 'TOP_FILM_LOADING';
const TOP_FILM_LOADED = 'TOP_FILM_LOADED';
const TOP_FILM_ERROR = 'TOP_FILM_ERROR';
const TOP_FILM_CLEAR = 'TOP_FILM_CLEAR';

export default {
	TOP_FILM_LOADING,
	TOP_FILM_LOADED,
	TOP_FILM_ERROR,
	TOP_FILM_CLEAR,
} as const;
