const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
const NOTIFICATION_PERMISSION_GRANTED = 'NOTIFICATION_PERMISSION_GRANTED';
const NOTIFICATION_PERMISSION_DENIED = 'NOTIFICATION_PERMISSION_DENIED';
const WS_CONNECTED = 'WS_CONNECTED';
const WS_DISCONNECTED = 'WS_DISCONNECTED';
const SET_NOTIFICATION_ERROR = 'SET_NOTIFICATION_ERROR';

export default {
	NOTIFICATION_RECEIVED,
	NOTIFICATION_PERMISSION_GRANTED,
	NOTIFICATION_PERMISSION_DENIED,
	WS_CONNECTED,
	WS_DISCONNECTED,
	SET_NOTIFICATION_ERROR,
} as const;
