const ACTOR_LOADING = 'ACTOR_LOADING';
const ACTOR_LOADED = 'ACTOR_LOADED';
const ACTOR_ERROR = 'ACTOR_ERROR';

const ACTOR_FILMS_LOADING = 'ACTOR_FILMS_LOADING';
const ACTOR_FILMS_LOADED = 'ACTOR_FILMS_LOADED';
const ACTOR_FILMS_ERROR = 'ACTOR_FILMS_ERROR';

export default {
	ACTOR_LOADING,
	ACTOR_LOADED,
	ACTOR_ERROR,
	ACTOR_FILMS_LOADING,
	ACTOR_FILMS_LOADED,
	ACTOR_FILMS_ERROR,
} as const;
