const MESSAGE_LOADING = 'MESSAGE_LOADING';
const MESSAGE_LOADED = 'MESSAGE_LOADED';
const MESSAGE_ERROR = 'MESSAGE_ERROR';

export default {
	MESSAGE_LOADING,
	MESSAGE_LOADED,
	MESSAGE_ERROR,
} as const;
