name: Linter

on:
  push:
  pull_request:
    types: [opened]

permissions:
  checks: write
  contents: write

jobs:
  install-cache:
    name: Install cache
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v5

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci

  eslint-check:
    name: Eslint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Run ESLint
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          auto_fix: true

  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Run Prettier
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
          auto_fix: true

  stylelint-check:
    name: Stylelint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Run Stylelint
        run: npm run lint:stylelint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - eslint-check
      - prettier-check
      - stylelint-check
    steps:
      - uses: actions/checkout@v5
      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Run build
        run: npm run build
